# Generated by Django 5.0.3 on 2026-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(default='Bronze', max_length=20),
        ),
    ]
