# Generated by Django 5.0.3 on 2026-05-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_user_rank_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chess_customizations',
            field=models.JSONField(blank=True, default=dict, help_text='Custom chess styling presets: {set, gradStart, gradEnd, stroke, shadow}'),
        ),
    ]
