# Generated by Django 5.0.3 on 2026-05-25 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(default='tictactoe', max_length=50)),
                ('player1_mmr_before', models.IntegerField()),
                ('player2_mmr_before', models.IntegerField()),
                ('player1_mmr_change', models.IntegerField(default=0)),
                ('player2_mmr_change', models.IntegerField(default=0)),
                ('player1_xp_gain', models.IntegerField(default=0)),
                ('player2_xp_gain', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='matches.match')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_as_p2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['player1', '-created_at'], name='rankings_ma_player1_d8e2d9_idx'), models.Index(fields=['player2', '-created_at'], name='rankings_ma_player2_de379b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(default='tictactoe', max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('mmr', models.IntegerField(default=1000)),
                ('last_match_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['game_type', '-mmr'], name='rankings_pl_game_ty_065fd1_idx'), models.Index(fields=['game_type', '-xp'], name='rankings_pl_game_ty_84cd24_idx')],
                'unique_together': {('user', 'game_type')},
            },
        ),
    ]
