# Generated by Django 5.0.3 on 2026-05-22 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('game_type', models.CharField(default='tictactoe', max_length=50)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_prize_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_participants', models.PositiveIntegerField(default=16)),
                ('current_participants_count', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
