# Generated by Django 5.0.3 on 2026-05-25 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='total_prize_pool',
            new_name='prize_pool',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='current_participants_count',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='rank',
        ),
        migrations.AddField(
            model_name='tournament',
            name='bracket_type',
            field=models.CharField(choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('swiss', 'Swiss')], default='single_elimination', max_length=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Default Tournament', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='current_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('registering', 'Registration Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registering', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_order', models.IntegerField()),
                ('match_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Not Started'), ('active', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to='tournaments.tournamentparticipant')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='tournaments.tournamentparticipant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.tournamentparticipant')),
            ],
            options={
                'ordering': ['round_number', 'match_order'],
                'unique_together': {('tournament', 'round_number', 'match_order')},
            },
        ),
    ]
