# Generated by Django 5.0.3 on 2026-05-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwissRoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['tournament', 'round_number', '-points'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tournamentmatch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_swiss_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qualification_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='swiss_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('knockout', 'Pure Knockout'), ('swiss_hybrid', 'Swiss Hybrid')], default='knockout', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round_type',
            field=models.CharField(choices=[('play_in', 'Play‑in Round'), ('swiss', 'Swiss Round'), ('knockout', 'Knockout Round')], default='knockout', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='swiss_game_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='swiss_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentmatch',
            unique_together={('tournament', 'round_number', 'match_order', 'round_type')},
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'swiss_points'], name='tournaments_tournam_9b65f2_idx'),
        ),
        migrations.AddField(
            model_name='swissroundscore',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournamentmatch'),
        ),
        migrations.AddField(
            model_name='swissroundscore',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swiss_scores_as_opponent', to='tournaments.tournamentparticipant'),
        ),
        migrations.AddField(
            model_name='swissroundscore',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiss_scores_as_participant', to='tournaments.tournamentparticipant'),
        ),
        migrations.AddField(
            model_name='swissroundscore',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiss_scores', to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='swissroundscore',
            unique_together={('tournament', 'participant', 'round_number')},
        ),
    ]
