# Generated by Django 5.0.3 on 2026-05-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_swissroundscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
