# Generated by Django 5.0.3 on 2026-05-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='board_theme',
            field=models.CharField(default='random', max_length=50),
        ),
    ]
