export enum WSEvent {
  MATCH_START = 'MATCH_START',
  MOVE_MADE = 'MOVE_MADE',
  GAME_OVER = 'GAME_OVER',
  ERROR = 'ERROR',
  MAKE_MOVE = 'MAKE_MOVE',
  PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
  PAYOUT_TRIGGERED = 'PAYOUT_TRIGGERED'
}
