export const WSEvent = {
  MATCH_START: 'MATCH_START',
  MOVE_MADE: 'MOVE_MADE',
  TURN_SKIP: 'TURN_SKIP',
  GAME_OVER: 'GAME_OVER',
  ERROR: 'ERROR',
  MAKE_MOVE: 'MAKE_MOVE',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  PAYOUT_TRIGGERED: 'PAYOUT_TRIGGERED',
  NEXT_MATCH: 'NEXT_MATCH',
} as const;

export type WSEventType = typeof WSEvent[keyof typeof WSEvent];
